version: '3.1'

services:
  command-line-demo-database:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: commandline-demo-db
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5436:5432
    container_name: command-line-demo-database
    volumes:
      - pgdata12:/var/lib/postgresql/data
volumes:
  pgdata12:
    driver: local
